name: matrix_ex
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 6
      matrix:
        
        os: [ubuntu-latest , windows-latest]
        node: [16,20,22]
        exclude:
          - node: 16
            os: windows-latest
        include:
          - node: 24
            os: windows-latest
    steps:
      - name: checkcode
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v7
        with:
           node-version: ${{matrix.node}}
      - name: caches
        uses: actions/cache@v6
        id: caches
        with:
          path: node_modules
          key: deps-node-modules-${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - name: dep
        if: steps.caches.outputs.cache-hit != 'true'
        run: npm ci
      - name: build
        run: npm run build





      
