name: the_reusable
on: 
  workflow_call:
    inputs:
      downloadable:
        required: true
        type: string
      path:
        type: string
        required: false
        default: ./dist
    secrets:
      sec:
        required: false
    outputs:
      result:
        value: ${{jobs.download.outputs.outcome}}
jobs:
  download:
    runs-on: ubuntu-22.04
    outputs:
      outcome: ${{steps.output.outputs.MEDO}}
    steps:
      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{inputs.downloadable}}
          path: ${{inputs.path}}
      -  run: |
           cd ${{inputs.path}}
           ls
      -  run: echo "${{secrets.sec}}"
      -  run: echo "MEDO=DevOps" >> $GITHUB_OUTPUT
         id: output
