name: the reusable workflow
on: 
  workflow_call:
    inputs:
      artifact:
        type: string
        description: its needed 
      path:
        type: string
        required: true
      envs:
        type: string
        required: true
      environment:
        type: string
        required: false
    secrets:
      sec:
        required: true
    
        
jobs:
  first:
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: echo "Hi evey one this is the deployment demo"
  sec:
     runs-on: ubuntu-latest
     steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v6
        with: 
          name: ${{inputs.artifact}}
          path: ${{inputs.path}}
         
      - name: Output contents
        run: |
          cd ./dist
        
          ls
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "${{secrets.sec}}"
          echo "${{inputs.envs}}"
        
