name: the reusable workflow
on: 

  workflow_call:
    inputs:
      artifact:
        type: string
        description: its needed 
      path:
        type: string
        required: true
      envs:
        type: string
        required: true
      environment:
        type: string
        required: false
    secrets:
      sec:
        required: true
    outputs:
      result:
        value: ${{jobs.first.outputs.outcome}}
    

jobs:
  first:
    outputs:
      outcome: ${{steps.produce.outputs.WILIAM}}
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: echo "Hi evey one this is the deployment demo"
      - name: this will produce output
        id: produce
        run: ehco "WILIAM=DevOps" >> $GITHUB_OUTPUT
  sec:
     runs-on: ubuntu-latest
     environment: ${{inputs.environment}}
     steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v6
        with: 
          name: ${{inputs.artifact}}
          path: ${{inputs.path}}
         
      - name: Output contents
        run: |
          cd ./dist
        
          ls
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "${{secrets.sec}}"
          echo "${{vars.X}}"
          echo "${{inputs.envs}}"
        
